### ISSUE TITLE
OverflowError  with csv.field_size_limit(sys.maxsize)

### ISSUE THREAD

**Issue by TheMrSheldon** [mrjleo/qa-utils#4]
Simply running
```python
import ranking_utils.datasets.trec
```
crashes for me with an overflow error: "OverflowError: Python int too large to convert to C long".
The issue lies with calling
```python
csv.field_size_limit(sys.maxsize)
```
since, according to [python's documentation](https://docs.python.org/3/library/sys.html#sys.maxsize), `sys.maxsize` returns the largest number representable by [`Py_ssize_t`](https://docs.python.org/3/c-api/intro.html#c.Py_ssize_t) but csv requires the argument as a long.
On my system (Windows 64 bit) `Py_ssize_t` is 64 bit long but a long is only 32 bit long, thus leading to the error.

One way to mitigate this issue would be to calculate the maximum value a signed long could hold using ctypes and pass it instead:
```python
import ctypes
max_long = 2 ** (8*ctypes.sizeof(ctypes.c_long) - 1) - 1
csv.field_size_limit(max_long)
```

**Comment by mrjleo** [comment]
Good catch, thank you! I'll have a look in the coming days.

**Comment by mrjleo** [comment]
Hi @TheMrSheldon, I saw you already implemented the fix in your fork. I'd be happy to accept a PR!

**Comment by TheMrSheldon** [comment]
Thank you very much for your response. I have opened a pull request.

**Comment by mrjleo** [comment]
Thanks a lot!
